# Generated by Django 4.1.3 on 2023-01-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
