# Generated by Django 4.1.3 on 2023-01-10 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
