# Generated by Django 4.1.3 on 2023-01-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_telegram_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_token',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
    ]
