version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000


  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
       - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
        - redis:/data

  worker:
    build:
      context: ./
    hostname: worker
    entrypoint: celery
    command: -A drf_auth_with_celery worker --loglevel=info
    volumes:
      - ./api:/app
    links:
      - redis
    depends_on:
      - redis
volumes:
  redis:
    driver: local