# Generated by Django 4.1.3 on 2023-01-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
    ]
